service: cvs-svc-test-station
useDotenv: true
configValidationMode: warn
plugins:
  - serverless-dynamodb
  - serverless-plugin-typescript
  - serverless-plugin-tracing
  - serverless-offline
  - serverless-offline-aws-eventbridge

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs18.x
  tracing:
    apiGateway: true
    lambda: true
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  getTestStations:
    handler: src/handler.handler
    events:
      - http:
          path: test-stations
          method: get
      - http:
          path: test-stations/{testStationPNumber}
          method: get
          request:
            parameters:
              paths:
                testStationPNumber: true
  consumeEvent:
    handler: src/handler.consume
    environment:
      BRANCH: local
    events:
      - eventBridge:
          pattern:
            source:
              - cvs.update.test.stations

custom:
  dotenv:
    basePath: "./"
  serverless-offline:
    httpPort: 3004
  serverless-dynamodb:
    stages:
      - dev
      - test
    start:
      port: 8007
      inMemory: true
      migrate: true
      seed: true
      noStart: false
      host: 127.0.0.1
    seed:
      test-stations:
        sources:
          - table: cvs-local-test-stations
            sources: [./tests/resources/test-stations.json]
  serverless-offline-aws-eventbridge:
    port: 4010
    mockEventBridgeServer: true
    hostname: 127.0.0.1
    debug: true
    account: '1234567'

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-stations
        AttributeDefinitions:
          - AttributeName: testStationId
            AttributeType: S
          - AttributeName: testStationPNumber
            AttributeType: S
        KeySchema:
          - AttributeName: testStationId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: testStationPNumberIndex
            KeySchema:
              - AttributeName: testStationPNumber
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - testStationEmails
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: "1"
              WriteCapacityUnits: "1"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
