name: Build hash and deploy to S3
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+-[0-9]+-[0-9]+.[0-9]+'

jobs:
  Build:
    uses: dvsa/cvs-github-actions/.github/workflows/build-node-hash.yaml@feature/CB2-11035
    secrets:
      CVS_MGMT_AWS_ROLE: ${{ secrets.CVS_MGMT_AWS_ROLE }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
