name: Build hash and deploy to S3
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/CB2-10412'

jobs:
  Build:
    uses: dvsa/cvs-github-actions/.github/workflows/build-node-hash.yaml@feature/CB2-10412
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
      short_repo_name: ${{ inputs.short_repo_name }}
    secrets:
     AWS_MGMT_ROLE: ${{ secrets.AWS_MGMT_ROLE }}
     AWS_ROLE: ${{ secrets.AWS_ROLE }}
     DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}